version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: /backend/foodgram/.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ekblb/foodgram_backend
    env_file: /backend/foodgram/.env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on: 
      - db
  frontend:
    image: ekblb/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: ekblb/foodgram_gateway
    env_file: /backend/foodgram/.env
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/