version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ekblb/foodgram_backend
    # env_file: .env
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on: 
      - db
  frontend:
    image: ekblb/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/