# Generated by Django 4.2.5 on 2023-12-18 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть меньше 1.'), django.core.validators.MaxValueValidator(limit_value=2147483647, message='Значение не может быть больше 2147483647 мин.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть меньше 1 мин.'), django.core.validators.MaxValueValidator(limit_value=2147483647, message='Значение не может быть больше 2147483647 мин.')], verbose_name='Время приготовления (мин.)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
